title: Lucidní snění
baseURL: https://gallant-jang-a859c1.netlify.com
languageCode: cs-cz
publishDir: public

menu:
  main:
    - name: Homepage
      url: /
      weight: 10
    - name: Tvorba moodboardu pro náš web
      identifier: post
      url: /post/
      weight: 20


params:
  description: Description of my new site.
  authors: Authors

